///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAgile = 'assets/icons/agile.png';
  static const String iconsAndroidStudio = 'assets/icons/android_studio.png';
  static const String iconsAppStore = 'assets/icons/app_Store.png';
  static const String iconsAtlassian = 'assets/icons/atlassian.png';
  static const String iconsChat = 'assets/icons/chat.png';
  static const String iconsDart = 'assets/icons/dart.png';
  static const String iconsDocker = 'assets/icons/docker.png';
  static const String iconsECommercApp = 'assets/icons/e_commerc_app.png';
  static const String iconsFacebook = 'assets/icons/facebook.png';
  static const String iconsFigma = 'assets/icons/figma.png';
  static const String iconsFirebase = 'assets/icons/firebase.png';
  static const String iconsFlutter = 'assets/icons/flutter.png';
  static const String iconsGithub = 'assets/icons/github.png';
  static const String iconsGmail = 'assets/icons/gmail.png';
  static const String iconsGooglePlay = 'assets/icons/google_play.png';
  static const String iconsKotlin = 'assets/icons/kotlin.png';
  static const String iconsLinkedin = 'assets/icons/linkedin.png';
  static const String iconsMedking = 'assets/icons/medking.png';
  static const String iconsMideo = 'assets/icons/mideo.png';
  static const String iconsNotion = 'assets/icons/notion.png';
  static const String iconsPointCounter = 'assets/icons/point_counter.png';
  static const String iconsPostman = 'assets/icons/postman.png';
  static const String iconsPostsApp = 'assets/icons/posts_app.png';
  static const String iconsRestful = 'assets/icons/restful.png';
  static const String iconsSkyCast = 'assets/icons/sky_cast.png';
  static const String iconsSql = 'assets/icons/sql.png';
  static const String iconsSupabase = 'assets/icons/supabase.png';
  static const String iconsTaseese = 'assets/icons/taseese.png';
  static const String iconsToDoDo = 'assets/icons/to_do_do.png';
  static const String iconsVscode = 'assets/icons/vscode.png';
  static const String iconsXd = 'assets/icons/xd.png';
  static const String iconsXo = 'assets/icons/xo.png';
  static const String iconsYoutube = 'assets/icons/youtube.png';
  static const String imagesCatchDataInFlutter =
      'assets/images/catch_data_in_flutter.png';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesMe = 'assets/images/me.jpg';
  static const String imagesPagination = 'assets/images/pagination.png';
  static const String lottieChat1 = 'assets/lottie/chat1.json';
  static const String lottieChat2 = 'assets/lottie/chat2.json';
  static const String lottieFacebook = 'assets/lottie/facebook.json';
  static const String lottieGithub = 'assets/lottie/github.json';
  static const String lottieGmail = 'assets/lottie/gmail.json';
  static const String lottieLinkedin = 'assets/lottie/linkedin.json';
  static const String lottieYoutube = 'assets/lottie/youtube.json';
  static const String playfairDisplayPlayfairDisplayBlack =
      'assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf';
  static const String playfairDisplayPlayfairDisplayBlackItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf';
  static const String playfairDisplayPlayfairDisplayBold =
      'assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf';
  static const String playfairDisplayPlayfairDisplayBoldItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf';
  static const String playfairDisplayPlayfairDisplayExtraBold =
      'assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf';
  static const String playfairDisplayPlayfairDisplayExtraBoldItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBoldItalic.ttf';
  static const String playfairDisplayPlayfairDisplayItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf';
  static const String playfairDisplayPlayfairDisplayMedium =
      'assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf';
  static const String playfairDisplayPlayfairDisplayMediumItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-MediumItalic.ttf';
  static const String playfairDisplayPlayfairDisplayRegular =
      'assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf';
  static const String playfairDisplayPlayfairDisplaySemiBold =
      'assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf';
  static const String playfairDisplayPlayfairDisplaySemiBoldItalic =
      'assets/fonts/Playfair_Display/PlayfairDisplay-SemiBoldItalic.ttf';
  static const String robotoRobotoBlack =
      'assets/fonts/Roboto/Roboto-Black.ttf';
  static const String robotoRobotoBlackItalic =
      'assets/fonts/Roboto/Roboto-BlackItalic.ttf';
  static const String robotoRobotoBold = 'assets/fonts/Roboto/Roboto-Bold.ttf';
  static const String robotoRobotoBoldItalic =
      'assets/fonts/Roboto/Roboto-BoldItalic.ttf';
  static const String robotoRobotoItalic =
      'assets/fonts/Roboto/Roboto-Italic.ttf';
  static const String robotoRobotoLight =
      'assets/fonts/Roboto/Roboto-Light.ttf';
  static const String robotoRobotoLightItalic =
      'assets/fonts/Roboto/Roboto-LightItalic.ttf';
  static const String robotoRobotoMedium =
      'assets/fonts/Roboto/Roboto-Medium.ttf';
  static const String robotoRobotoMediumItalic =
      'assets/fonts/Roboto/Roboto-MediumItalic.ttf';
  static const String robotoRobotoRegular =
      'assets/fonts/Roboto/Roboto-Regular.ttf';
  static const String robotoRobotoThin = 'assets/fonts/Roboto/Roboto-Thin.ttf';
  static const String robotoRobotoThinItalic =
      'assets/fonts/Roboto/Roboto-ThinItalic.ttf';
  static const String translationsArEG = 'assets/translations/ar-EG.json';
  static const String translationsEnUS = 'assets/translations/en-US.json';
}
