// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEFRZSF3EJfWimsWcTBGxNjkCgUktCAc',
    appId: '1:915743315927:android:5ce3ef6235e1aed3f11d92',
    messagingSenderId: '915743315927',
    projectId: 'taseese-new-app',
    storageBucket: 'taseese-new-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMEozLWeyAwI0WbAZWfIrNMds0ugunNM8',
    appId: '1:915743315927:ios:c620a474b35d8b08f11d92',
    messagingSenderId: '915743315927',
    projectId: 'taseese-new-app',
    storageBucket: 'taseese-new-app.appspot.com',
    androidClientId: '915743315927-6mjusc0878jant43p125cc5laqmnrf7n.apps.googleusercontent.com',
    iosClientId: '915743315927-1kj8tnao1i2sq37e4fiokln3mmp9236g.apps.googleusercontent.com',
    iosBundleId: 'com.edutasses.tasesseApplication',
  );
}
