import 'dart:async';

import 'package:dartz/dartz.dart' hide State;
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/svg.dart';
import 'package:injectable/injectable.dart';
import 'package:my_portfolio/config/resources/app_assets.dart';
import 'package:my_portfolio/config/resources/app_colors.dart';
import 'package:my_portfolio/config/resources/app_strings.dart';
import 'package:my_portfolio/config/resources/app_text_style.dart';
import 'package:my_portfolio/config/resources/app_values.dart';
import 'package:my_portfolio/config/responsive/responsive_extensions.dart';
import 'package:my_portfolio/core/api/end_points.dart';
import 'package:my_portfolio/core/enum/enum_generation.dart';
import 'package:my_portfolio/core/services/services_locator.dart';
import 'package:my_portfolio/core/shared_widget/empty_list_widget.dart';
import 'package:my_portfolio/core/shared_widget/loading_shimmer_list.dart';
import 'package:my_portfolio/features/child_flow/home/domain/home_entities/subjects_entity.dart';
import 'package:my_portfolio/features/child_flow/questions/shared/data/go_to_question_parameter.dart';
import 'package:my_portfolio/my_app/app_reference.dart';
import '../../../../../../core/usecase/base_usecase.dart';
import '../../../../config/base_remote_data_source/base_remote_data_source.dart';
import '../../../../config/base_repository/base_repository.dart';
import '../../../../core/failure/failure.dart';
import '../../../config/resources/app_constants.dart';
import '../../../config/responsive/responsive_widget.dart';
import '../../../core/shared_models/user/data/user_local_data_source/user_local_data_source.dart';
import '../../shared_features/child_subscriptions/domain/child_subscriptions_usecases/get_child_subscriptions_subjects_use_case.dart';
import '../more/more_widgets/more_widgets.dart';
import '../more/presentation/more_widgets/header_for_more.dart';
import 'presentation/rank_screen/rank_data.dart';

part 'data/rank_data_source/rank_remote_data_source.dart';
part 'data/rank_models/rank_model.dart';
part 'data/rank_repository/rank_repository.dart';
part 'domain/rank_base_repository/rank_base_repository.dart';
part 'domain/rank_entities/rank_entity.dart';
part 'domain/rank_usecases/rank_usecase.dart';
part 'presentation/rank_screen/rank_screen.dart';
// part 'presentation/rank_screen/rank_type_screen.dart';
part 'presentation/rank_view_model/rank_bloc.dart';
part 'presentation/rank_view_model/rank_event.dart';
part 'presentation/rank_view_model/rank_state.dart';
part 'presentation/rank_widgets/rank_widgets.dart';
