import 'package:dartz/dartz.dart' hide State;
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:my_portfolio/config/resources/app_strings.dart';
import 'package:my_portfolio/config/resources/app_text_style.dart';
import 'package:my_portfolio/config/responsive/responsive_extensions.dart';
import 'package:my_portfolio/core/api/end_points.dart';
import 'package:my_portfolio/core/enum/enum_generation.dart';
import 'package:my_portfolio/core/shared_widget/header_for_terms_levels_collections.dart';
import 'package:my_portfolio/features/child_flow/questions/collections/data/collections_models/collection_model.dart';
import 'package:my_portfolio/features/child_flow/questions/collections/presentation/collections_widgets/child/child_collection_builder.dart';
import 'package:my_portfolio/features/child_flow/questions/collections/presentation/collections_widgets/level_name_widget.dart';
import 'package:my_portfolio/my_app/app_analytics.dart';
import '../../../../../../core/usecase/base_usecase.dart';
import '../../../../config/base_remote_data_source/base_remote_data_source.dart';
import '../../../../config/base_repository/base_repository.dart';
import '../../../../config/resources/app_values.dart';
import '../../../../config/routes/route_manager.dart';
import '../../../../config/routes/routes_names.dart';
import '../../../../core/failure/failure.dart';
import '../../../../core/services/services_locator.dart';
import '../shared/data/go_to_question_parameter.dart';
import '../shared/data/go_to_questions_data.dart';
import '../shared/entity/levels_group_entity.dart';


part 'data/collections_data_source/collections_remote_data_source.dart';
part 'data/collections_repository/collections_repository.dart';
part 'domain/collections_base_repository/collections_base_repository.dart';
part 'domain/collections_usecases/collections_usecase.dart';
part 'presentation/collections_screen/collections_screen.dart';
part 'presentation/collections_view_model/collections_bloc.dart';
part 'presentation/collections_view_model/collections_event.dart';
part 'presentation/collections_view_model/collections_state.dart';
